<%@ Page Title="" Language="C#" Async="true" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="DashWerknemer.aspx.cs" Inherits="WebsiteJIT_MatteoScaringi.DashWerknemer" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .height {
            height: 85vh;
        }
        .card {
            margin-top: auto;
            margin-bottom: auto;
        }
        .btn-primary {
            background-color: #012f5c;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <asp:GridView ID="InschrijvingGrid" runat="server" AutoGenerateColumns="false" DataKeyNames="_id" OnSelectedIndexChanged="InschrijvingGrid_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="InschrijvingGrid_RowDeleting">
        <Columns>
            <asp:BoundField DataField="_id" HeaderText="Inschrijvingsnummer" />
            <asp:BoundField DataField="_datum" HeaderText="Datum" />
            <asp:BoundField DataField="_voorbereidingid" HeaderText="Voorebereidingsnummer" />
            <asp:BoundField DataField="_aanmeldid" HeaderText="Lidnummer" />
        </Columns>
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    </asp:GridView>
    
    <asp:GridView ID="VoorbereidingGrid" runat="server" AutoGenerateColumns="false" DataKeyNames="_id" OnSelectedIndexChanged="VoorbereidingGrid_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="InschrijvingGrid_RowDeleting">
        <Columns>
            <asp:BoundField DataField="_id" HeaderText="Voorbereidingsnummer" />
            <asp:BoundField DataField="_medewerkerid" HeaderText="Weknemer" />
            <asp:BoundField DataField="_inhoud" HeaderText="Inhoud" />
            <asp:BoundField DataField="_duur" HeaderText="Duur" />
        </Columns>
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    </asp:GridView>
    
    <asp:GridView ID="GebruikerGrid" runat="server" AutoGenerateColumns="false" DataKeyNames="_id" OnSelectedIndexChanged="GebruikerGrid_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
        <Columns>
            <asp:BoundField DataField="_id" HeaderText="Lidnummer" />
            <asp:BoundField DataField="_naam" HeaderText="Naam" />
            <asp:BoundField DataField="_telnr" HeaderText="Tel." />
            <asp:BoundField DataField="_adres" HeaderText="Adres" />
            <asp:BoundField DataField="_email" HeaderText="E-Mail" />
            <asp:BoundField DataField="_wachtwoord" HeaderText="Wachtwoord" />
            <asp:BoundField DataField="_rol" HeaderText="Rol" />
        </Columns>
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    </asp:GridView>

</asp:Content>
