<%@ Page Title="" Language="C#" Async="true" MasterPageFile="~/Main.Master" AutoEventWireup="true" CodeBehind="DashWerknemer.aspx.cs" Inherits="WebsiteJIT_MatteoScaringi.DashWerknemer" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style>
        .height {
            height: 85vh;
        }
        .card {
            margin-top: auto;
            margin-bottom: auto;
        }
        .btn-primary {
            background-color: #012f5c;
        }
    </style>
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

<%--    <div class="container height d-flex flex-column align-items-center justify-content-center">
        <div class="row justify-content-center w-100">
            <div class="col-md-4"> <!-- Decrease the width as needed -->
                <div class="card">
                    <div class="card-body">
                        <div class="form-container">
                            <asp:Button ID="btnInschrijving" runat="server" Text="Inschrijvingen beheren" CssClass="btn btn-primary w-100 mb-2" />
                            <asp:Button ID="btnVoorbereidingen" runat="server" Text="Voorbereidingen beheren" CssClass="btn btn-primary w-100 mb-2" />
                            <asp:Button ID="btnGebruikers" runat="server" Text="Gebruikers beheren" CssClass="btn btn-primary w-100 mb-2"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>--%>
    
    <asp:GridView ID="InschrijvingGrid" runat="server" AutoGenerateColumns="false" DataKeyNames="_id" OnSelectedIndexChanged="InschrijvingGrid_SelectedIndexChanged" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="InschrijvingGrid_RowDeleting">
        <Columns>
            <asp:BoundField DataField="_id" HeaderText="Inschrijvingsnummer" />
            <asp:BoundField DataField="_datum" HeaderText="Datum" />
            <asp:BoundField DataField="_voorbereidingid" HeaderText="Voorebereidingsnummer" />
            <asp:BoundField DataField="_aanmeldid" HeaderText="Lidnummer" />
        </Columns>
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
    </asp:GridView>

</asp:Content>
